import { useEffect, useMemo, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Sparkles, RefreshCw, CheckCircle2, AlertCircle, Save } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { IVMedication } from "../IVDilutionAdminPage";
import { generateAllTexts, computeTextIssues, type GeneratedTexts } from "../lib/ivTextGenerator";
import { logIVTextChange } from "../lib/ivTextLog";

type Props = {
  medication: IVMedication & Partial<GeneratedTexts> & {
    texto_gerado_automaticamente?: boolean;
    status_texto?: string | null;
    data_geracao_texto?: string | null;
    data_revisao_texto?: string | null;
  };
  open: boolean;
  onClose: () => void;
  onSaved?: () => void;
  canEdit: boolean;
  canApprove: boolean;
};

const FIELDS: { key: keyof GeneratedTexts; label: string; help: string }[] = [
  { key: "alerta_medico", label: "Alerta médico", help: "Texto curto exibido ao prescritor." },
  { key: "alerta_enfermagem_farmacia", label: "Orientação para enfermagem / farmácia", help: "Texto operacional de preparo e administração." },
  { key: "orientacao_resumida_prescricao", label: "Orientação resumida para prescrição", help: "Resumo exibido no card durante a prescrição." },
  { key: "orientacao_para_impressao", label: "Orientação para impressão (PDF)", help: "Texto formal usado em documentos impressos." },
  { key: "mensagem_revisao_seguranca_iv", label: "Mensagem da Revisão de Segurança IV", help: "Resumo do risco principal." },
];

const TextStatusBadge = ({ s }: { s?: string | null }) => {
  const map: Record<string, string> = {
    gerado_automaticamente: "bg-secondary text-secondary-foreground border-border",
    aguardando_revisao: "bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/30",
    revisado: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/30",
    precisa_ajuste: "bg-destructive/10 text-destructive border-destructive/30",
    manual: "bg-primary/10 text-primary border-primary/30",
  };
  const labels: Record<string, string> = {
    gerado_automaticamente: "Texto automático",
    aguardando_revisao: "Texto pendente",
    revisado: "Texto revisado",
    precisa_ajuste: "Precisa ajuste",
    manual: "Texto manual",
  };
  if (!s) return <Badge variant="outline">Sem status</Badge>;
  return <Badge variant="outline" className={map[s]}>{labels[s] ?? s}</Badge>;
};

export default function IVTextsDialog({ medication, open, onClose, onSaved, canEdit, canApprove }: Props) {
  const [draft, setDraft] = useState<GeneratedTexts>({
    alerta_medico: medication.alerta_medico ?? "",
    alerta_enfermagem_farmacia: medication.alerta_enfermagem_farmacia ?? "",
    orientacao_resumida_prescricao: medication.orientacao_resumida_prescricao ?? "",
    orientacao_para_impressao: medication.orientacao_para_impressao ?? "",
    mensagem_revisao_seguranca_iv: medication.mensagem_revisao_seguranca_iv ?? "",
  });
  const [autoGenerated, setAutoGenerated] = useState<boolean>(!!medication.texto_gerado_automaticamente);
  const [status, setStatus] = useState<string>(medication.status_texto ?? (Object.values(draft).some(Boolean) ? "manual" : "aguardando_revisao"));
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setDraft({
      alerta_medico: medication.alerta_medico ?? "",
      alerta_enfermagem_farmacia: medication.alerta_enfermagem_farmacia ?? "",
      orientacao_resumida_prescricao: medication.orientacao_resumida_prescricao ?? "",
      orientacao_para_impressao: medication.orientacao_para_impressao ?? "",
      mensagem_revisao_seguranca_iv: medication.mensagem_revisao_seguranca_iv ?? "",
    });
    setAutoGenerated(!!medication.texto_gerado_automaticamente);
    setStatus(medication.status_texto ?? "aguardando_revisao");
  }, [medication.id]);

  const issues = useMemo(() => computeTextIssues({ ...medication, ...draft, status_texto: status, texto_gerado_automaticamente: autoGenerated }), [draft, medication, status, autoGenerated]);

  const handleGenerateAll = () => {
    setDraft(generateAllTexts(medication));
    setAutoGenerated(true);
    setStatus("aguardando_revisao");
    toast.success("Textos gerados. Revise antes de salvar.");
  };

  const handleRegenerate = (key: keyof GeneratedTexts) => {
    const all = generateAllTexts(medication);
    setDraft((d) => ({ ...d, [key]: all[key] }));
    setAutoGenerated(true);
  };

  const persist = async (newStatus: string, action: "gerou_texto" | "editou_texto" | "aprovou_texto" | "marcou_precisa_ajuste" | "substituiu_por_manual") => {
    setSaving(true);
    const { data: u } = await supabase.auth.getUser();
    const payload: any = {
      ...draft,
      texto_gerado_automaticamente: autoGenerated,
      status_texto: newStatus,
      data_geracao_texto: autoGenerated ? new Date().toISOString() : (medication.data_geracao_texto ?? null),
    };
    if (newStatus === "revisado") {
      payload.texto_revisado_por = u.user?.id ?? null;
      payload.data_revisao_texto = new Date().toISOString();
    }
    const { error } = await (supabase as any).from("iv_medications").update(payload).eq("id", medication.id);
    setSaving(false);
    if (error) { toast.error("Erro ao salvar textos"); return; }

    // Log per modified field
    for (const f of FIELDS) {
      const prev = (medication as any)[f.key] ?? null;
      const next = draft[f.key] ?? null;
      if (prev !== next) {
        logIVTextChange({
          id_medicamento: medication.id,
          principio_ativo: medication.principio_ativo,
          campo_texto_alterado: f.key,
          valor_anterior: prev,
          valor_novo: next,
          tipo_acao: action,
        });
      }
    }
    toast.success("Textos salvos.");
    onSaved?.();
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex flex-wrap items-center gap-2">
            Textos e orientações — {medication.principio_ativo}
            <TextStatusBadge s={status} />
          </DialogTitle>
        </DialogHeader>

        <div className="flex flex-wrap items-center gap-2 pb-2">
          <Button size="sm" onClick={handleGenerateAll} disabled={!canEdit}>
            <Sparkles className="h-4 w-4 mr-1" /> Gerar textos
          </Button>
          {autoGenerated && (
            <p className="text-xs text-amber-700 dark:text-amber-400 flex items-center gap-1">
              <AlertCircle className="h-3 w-3" /> Texto gerado automaticamente. Revise antes de uso clínico.
            </p>
          )}
        </div>

        {issues.length > 0 && (
          <div className="rounded-md border border-amber-500/30 bg-amber-500/5 p-2 text-xs text-amber-800 dark:text-amber-300 space-y-1">
            <p className="font-medium">Pendências de qualidade:</p>
            <ul className="list-disc pl-4">
              {issues.map((i) => <li key={i.code}>{i.message}</li>)}
            </ul>
          </div>
        )}

        <div className="space-y-4 pt-2">
          {FIELDS.map((f) => (
            <div key={f.key} className="space-y-1.5">
              <div className="flex items-center justify-between gap-2">
                <label className="text-sm font-medium">{f.label}</label>
                <Button size="sm" variant="ghost" disabled={!canEdit} onClick={() => handleRegenerate(f.key)}>
                  <RefreshCw className="h-3.5 w-3.5 mr-1" /> Regenerar
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">{f.help}</p>
              <Textarea
                value={draft[f.key]}
                onChange={(e) => setDraft((d) => ({ ...d, [f.key]: e.target.value }))}
                rows={f.key === "alerta_enfermagem_farmacia" || f.key === "orientacao_para_impressao" ? 4 : 2}
                disabled={!canEdit}
              />
            </div>
          ))}
        </div>

        <p className="text-[11px] text-muted-foreground pt-3 border-t mt-3">
          Essas orientações são ferramentas de apoio à decisão clínica e devem ser validadas conforme protocolo
          institucional, farmácia clínica e condições do paciente.
        </p>

        <DialogFooter className="gap-2 flex-wrap">
          <Button variant="ghost" onClick={onClose}>Fechar</Button>
          {canEdit && (
            <>
              <Button variant="outline" disabled={saving} onClick={() => { setAutoGenerated(false); persist("manual", "substituiu_por_manual"); }}>
                Salvar como manual
              </Button>
              <Button variant="outline" disabled={saving} onClick={() => persist("precisa_ajuste", "marcou_precisa_ajuste")}>
                Marcar precisa ajuste
              </Button>
              <Button disabled={saving} onClick={() => persist("aguardando_revisao", autoGenerated ? "gerou_texto" : "editou_texto")}>
                <Save className="h-4 w-4 mr-1" /> Salvar
              </Button>
            </>
          )}
          {canApprove && (
            <Button variant="default" disabled={saving} onClick={() => persist("revisado", "aprovou_texto")}>
              <CheckCircle2 className="h-4 w-4 mr-1" /> Aprovar
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
